spring:
  application:
    name: SpringStalk

version: ${VERSION:0.0.1}

server:
  port: 5000

aws:
  region: ${AWS_REGION:eu-north-1}
  dynamodb:
    table-name: ${DYNAMODB_TABLE:springstalk-visits}

